# Copyright Statement:
#

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),)
TARGET_DEVICE := $(TARGET_PRODUCT)
endif

# if WIFI_DRIVER_MODULE_PATH is set empty by device.mk,
# driver module will be loaded by rc file, not by framework
# in this case, driver makefile will refer to WIFI_DRIVER_MODULE_PATH_FOR_DRV
# for driver path location
ifeq ($(WIFI_DRIVER_MODULE_PATH),)
WIFI_DRIVER_MODULE_PATH_IN_DRV := $(WIFI_DRIVER_MODULE_PATH_FOR_DRV)
else
WIFI_DRIVER_MODULE_PATH_IN_DRV := $(WIFI_DRIVER_MODULE_PATH)
endif

ifeq ($(WIFI_DRIVER_MODULE_NAME),)
WIFI_DRIVER_MODULE_NAME_IN_DRV := $(WIFI_DRIVER_MODULE_NAME_FOR_DRV)
else
WIFI_DRIVER_MODULE_NAME_IN_DRV := $(WIFI_DRIVER_MODULE_NAME)
endif

include $(CLEAR_VARS)
WIFI_PROJ_CONFIG_FILE := $(LOCAL_PATH)/config/$(TARGET_DEVICE).config


local_path_full := $(shell pwd)/$(LOCAL_PATH)
wifi_module_out_path := $(PRODUCT_OUT)$(WIFI_DRIVER_MODULE_PATH_IN_DRV)
wifi_module_target := $(wifi_module_out_path)
PRIVATE_DRIVER_OUT_DIR := $(PRODUCT_OUT)$(WIFI_DRIVER_MODULE_DIR)

#Default enable prealloc memory
CFG_MTK_PREALLOC_DRIVER := y

MTK_STRIP_DRIVER := y

LOCAL_KERNEL_CROSS_COMPILE := $(KERNEL_CROSS_COMPILE)

#current parameter name for target arch on VSB is $(TARGET_ARCH)
ifeq ($(TARGET_KERNEL_ARCH),)
TARGET_KERNEL_ARCH := $(TARGET_ARCH)
endif

#avoid $(KERNEL_OUT)is not defined
ifeq ($(KERNEL_OUT),)
KERNEL_OUT := $(PRODUCT_OUT)/obj/KERNEL_OBJ
endif

LOCAL_MODULE := $(WIFI_DRIVER_MODULE_NAME_IN_DRV)
LOCAL_MODULE_TAGS := optional
LOCAL_ADDITIONAL_DEPENDENCIES := $(wifi_module_target)

include $(BUILD_PHONY_PACKAGE)

$(LOCAL_ADDITIONAL_DEPENDENCIES): PRIVATE_DRIVER_LOCAL_DIR := $(local_path_full)
$(LOCAL_ADDITIONAL_DEPENDENCIES): $(INSTALLED_KERNEL_TARGET)
	$(hide) rm -rf $(PRIVATE_DRIVER_LOCAL_DIR)/.config
	$(hide) cp -f $(WIFI_PROJ_CONFIG_FILE) $(PRIVATE_DRIVER_LOCAL_DIR)/.config
	$(MAKE) -C $(KERNEL_OUT) M=$(PRIVATE_DRIVER_LOCAL_DIR) ARCH=$(TARGET_KERNEL_ARCH) CROSS_COMPILE=$(KERNEL_CROSS_COMPILE) CFG_MTK_PREALLOC_DRIVER=$(CFG_MTK_PREALLOC_DRIVER) modules
	$(MAKE) -C $(KERNEL_OUT) M=$(PRIVATE_DRIVER_LOCAL_DIR) ARCH=$(TARGET_KERNEL_ARCH) CROSS_COMPILE=$(KERNEL_CROSS_COMPILE) CFG_MTK_PREALLOC_DRIVER=$(CFG_MTK_PREALLOC_DRIVER) INSTALL_MOD_PATH=$(PRODUCT_OUT)/obj/KERNEL_OBJ modules_install
ifeq ($(MTK_STRIP_DRIVER), y)
	$(LOCAL_KERNEL_CROSS_COMPILE)strip -g $(PRIVATE_DRIVER_LOCAL_DIR)/$(WIFI_DRIVER_MODULE_NAME_IN_DRV).ko
	$(LOCAL_KERNEL_CROSS_COMPILE)strip -g $(PRIVATE_DRIVER_LOCAL_DIR)/$(WIFI_DRIVER_MODULE_NAME_IN_DRV)_prealloc.ko
endif
	$(hide) mkdir -p $(PRIVATE_DRIVER_OUT_DIR)
	$(hide) cp -f $(PRIVATE_DRIVER_LOCAL_DIR)/$(WIFI_DRIVER_MODULE_NAME_IN_DRV).ko $(PRIVATE_DRIVER_OUT_DIR)
ifeq ($(CFG_MTK_PREALLOC_DRIVER), y)
	$(hide) cp -f $(PRIVATE_DRIVER_LOCAL_DIR)/$(WIFI_DRIVER_MODULE_NAME_IN_DRV)_prealloc.ko $(PRIVATE_DRIVER_OUT_DIR)
endif
	$(MAKE) -C $(KERNEL_OUT) M=$(PRIVATE_DRIVER_LOCAL_DIR) ARCH=$(TARGET_KERNEL_ARCH) CROSS_COMPILE=$(KERNEL_CROSS_COMPILE) clean
local_path_full :=
wifi_module_out_path :=
wifi_module_target :=
